version: 1
disable_existing_loggers: False

formatters:
  verbose:
    format: '{levelname} {asctime} {module} {process:d} {thread:d} {message}'
    style: '{'
  simple:
    format: '{levelname} {message}'
    style: '{'

handlers:
  file:
    level: INFO
    class: logging.FileHandler
    filename: /app/logs/django.log
    formatter: verbose
  console:
    level: DEBUG
    class: logging.StreamHandler
    formatter: simple

loggers:
  django:
    handlers: [file, console]
    level: INFO
    propagate: True
  scriby_backend:
    handlers: [file, console]
    level: DEBUG
    propagate: True

root:
  level: INFO
  handlers: [console]
